name: Nightly builds

on:
  push:
    branches:
      - main
  schedule:
   - cron: "35 3 * * *"
  workflow_dispatch:

jobs:
  test-build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose

      - name: Build and Run Containers
        run: docker-compose up -d --build

      - name: Install pytest
        run: docker exec fastapi_container pip install pytest

      - name: Run Tests Inside the Container
        run: docker exec fastapi_container pytest src/tests

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/fastapi-beyond-CRUD:latest .
          docker push ghcr.io/${{ github.repository_owner }}/fastapi-beyond-CRUD:latest